config/routes.rb
Rails.application.routes.draw do
  get 'posts/dashboard'
  get 'posts/create'
  get 'posts/index'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :image_url, presence: true
    validates :content, presence: true

    before_save :clear_content

    def clear_content
        self.content = self.content.gsub "spoiler", " "
        self.content = self.content.gsub "SPOILER", " "
        self.content = self.content.gsub "Spoiler", " "
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard
  
  def index
    @posts = Post.order("created_at DESC")
  end

  def create
    @post = Post.create(title: params[:title], image_url: params[:image_url], content: params[:content] ) 
  end

  def dashboard  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog - Romina Maccarini</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container pt-5 ">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/create.html.erb
<% if @post.errors.any? %> 
    <div id="error_explanation" class="alert alert-danger" role="alert">
        <h4 class="alert-heading">No se pudo agregar el post</h4>
        <p>Encontramos <%= pluralize(@post.errors.count, "Problema") %></p>
        <hr>
        <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    
<% else %>
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Post subido con éxito!</h4>
        <hr>
        <p class="mb-0">Puedes encontrar la lista de todos tus post desde el inicio. 
            <a href="/" class="alert-link"> Ver lista completa de post </a>
        
        </p>
    </div>
<% end %>

app/views/posts/dashboard.html.erb
<h1>Agregar nuevo post</h1> 

<form id="create_posts" method="get" action="/posts/create">
    <div class="form-group">
        <label for="title">Titulo de publicación</label>
        <input name="title" type="text" class="form-control">
    </div>

    <div class="form-group"> 
        <label for="image_url">URL imagen post</label>
        <input name="image_url" type="text" class="form-control"> 
    </div>

    <div class="form-group">
        <label for="content">Contenido</label>
        <textarea name="content" class="form-control"> </textarea>
    </div>
        <button type="submit" class="btn btn-primary">Subir post</button> 
</form>

app/views/posts/index.html.erb
<nav class="navbar navbar-light bg-light justify-content-between"> <a class="navbar-brand">Post</a>
<%=  link_to "Agregar post", posts_dashboard_path, {class: 'btn btn-outline-success my-2 my-sm-0'} %>
</nav>
<table class="table">
    <thead>
        <td>Title</td>
        <td>Created</td>
        <td>Image</td>
        <td>Content</td>

    </thead>
    <% @posts.each do |post| %>
        <tr>
            <td><%= post.title %></td>
            <td><%= post.created_at %></td>
            <td><%= image_tag post.image_url, width: "200px" %></td>
            <td><%= post.content %></td>
        </tr>
    <% end %>

</table>